{% set name = "apache-airflow-providers-qubole" %}
{% set version = "3.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-qubole-{{ version }}.tar.gz
  sha256: e0d653c25e381df11f74835fe6446e256291b9aef653567e3cb119fe860b9edc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    - python >=3.7
    - apache-airflow-providers-common-sql >=1.3.0
    - apache-airflow >=2.3.0
    - qds-sdk >=1.10.4

test:
  imports:
    - airflow.providers.qubole
    - airflow.providers.qubole.hooks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Apache Airflow. Implements apache-airflow-providers-qubole package
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-qubole/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
